stages:
  - build


frontend_build-dev:
  stage: build
  tags:
    - react-front-dev
  script:
    - env
    - docker stop ReactFrontend-dev && docker rm ReactFrontend-dev && docker rmi frontend:latest
    - docker build -t frontend:latest .
    - docker run --name ReactFrontend-dev -id -p 3000:3000 frontend:latest
  only:
    - develop
