// SIGN UP
export const CREATE_NEW_USER = 'CREATE_NEW_USER'
export const CREATE_NEW_USER_REQUESTING = 'CREATE_NEW_USER_REQUESTING'
export const CREATE_NEW_USER_SUCCESS = 'CREATE_NEW_USER_SUCCESS'
export const CREATE_NEW_USER_ERROR = 'CREATE_NEW_USER_ERROR'
export const CANCEL_SIGN_UP = 'CANCEL_SIGN_UP'
export const GET_USER_BY_NAME = 'GET_USER_BY_NAME'
export const SIGNUP_FOODMAKER_REQUESTING = 'SIGNUP_FOODMAKER_REQUESTING'
export const SIGNUP_FOODMAKER_SUCCESS = 'SIGNUP_FOODMAKER_SUCCESS'
export const SIGNUP_FOODMAKER_ERROR = 'SIGNUP_FOODMAKER_ERROR'
export const SIGNUP_LOVER_AS_MAKER_REQUESTING = 'SIGNUP_LOVER_AS_MAKER_REQUESTING'
export const SIGNUP_LOVER_AS_MAKER_SUCCESS = 'SIGNUP_LOVER_AS_MAKER_SUCCESS'
export const SIGNUP_LOVER_AS_MAKER_ERROR = 'SIGNUP_LOVER_AS_MAKER_ERROR'

// Sign In
export const SIGNUP_REQUESTING = 'SIGNUP_REQUESTING'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_ERROR = 'SIGNUP_ERROR'
export const SIGNUP_FLAG_RESET = 'SIGNUP_FLAG_RESET'

// Login
export const LOGIN_REQUESTING = 'LOGIN_REQUESTING'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGIN_ERROR_RESET = 'LOGIN_ERROR_RESET'
export const LINK_ERROR_SET = 'LINK_ERROR_SET'

// Account
export const GET_USER_BY_LINK_REQUESTING = 'GET_USER_BY_LINK_REQUESTING'
export const GET_USER_BY_LINK_SUCCESS = 'GET_USER_BY_LINK_SUCCESS'
export const GET_USER_BY_LINK_ERROR = 'GET_USER_BY_LINK_ERROR'
export const GET_USER_ACCOUNT_REQUESTING = 'GET_USER_ACCOUNT_REQUESTING'
export const GET_USER_ACCOUNT_SUCCESS = 'GET_USER_ACCOUNT_SUCCESS'
export const GET_USER_ACCOUNT_ERROR = 'GET_USER_ACCOUNT_ERROR'
export const UPDATE_ACCOUNT_REQUESTING = 'UPDATE_ACCOUNT_REQUESTING'
export const UPDATE_ACCOUNT_SUCCESS = 'UPDATE_ACCOUNT_SUCCESS'
export const UPDATE_ACCOUNT_ERROR = 'UPDATE_ACCOUNT_ERROR'
export const RESET_CONFIRMATION = 'RESET_CONFIRMATION'
export const UPDATE_PHOTO_NAME_REQUESTING = 'UPDATE_PHOTO_NAME_REQUESTING'
export const UPDATE_PHOTO_NAME_SUCCESS = 'UPDATE_PHOTO_NAME_SUCCESS'
export const UPDATE_PHOTO_NAME_ERROR = 'UPDATE_PHOTO_NAME_ERROR'
export const UPDATE_FOODMAKER_ACCOUNT_REQUESTING = 'UPDATE_FOODMAKER_ACCOUNT_REQUESTING'
export const UPDATE_FOODMAKER_ACCOUNT_SUCCESS = 'UPDATE_FOODMAKER_ACCOUNT_SUCCESS'
export const UPDATE_FOODMAKER_ACCOUNT_ERROR = 'UPDATE_FOODMAKER_ACCOUNT_ERROR'

// Forgot STEP 1
export const PASSWORD_REQUESTING = 'PASSWORD_REQUESTING'
export const PASSWORD_REQUESTING_SUCCESS = 'PASSWORD_REQUESTING_SUCCESS'
export const PASSWORD_REQUESTING_ERROR = 'PASSWORD_REQUESTING_ERROR'

// Forgot STEP 1
export const PASSWORD_CREATING = 'PASSWORD_CREATING'
export const PASSWORD_CREATING_SUCCESS = 'PASSWORD_CREATING_SUCCESS'
export const PASSWORD_CREATING_ERROR = 'PASSWORD_CREATING_ERROR'

// Change email
export const CHANGE_EMAIL_REQUESTING = 'CHANGE_EMAIL_REQUESTING'
export const CHANGE_EMAIL_REQUESTING_SUCCESS = 'CHANGE_EMAIL_REQUESTING_SUCCESS'
export const CHANGE_EMAIL_REQUESTING_ERROR = 'CHANGE_EMAIL_REQUESTING_ERROR'
export const EMAIL_CONFIRM = 'EMAIL_CONFIRM'
export const EMAIL_CONFIRM_SUCCESS = 'EMAIL_CONFIRM_SUCCESS'
export const EMAIL_CONFIRM_ERROR = 'EMAIL_CONFIRM_ERROR'

// Listing
export const GET_MY_PRODUCT_LIST_REQUESTING = 'GET_MY_PRODUCT_LIST_REQUESTING'
export const GET_MY_PRODUCT_LIST_SUCCESS = 'GET_MY_PRODUCT_LIST_SUCCESS'
export const GET_MY_PRODUCT_LIST_ERROR = 'GET_MY_PRODUCT_LIST_ERROR'

// Product
export const CREATE_PRODUCT_REQUESTING = 'CREATE_PRODUCT_REQUESTING'
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS'
export const CREATE_PRODUCT_ERROR = 'CREATE_PRODUCT_ERROR'
export const UPDATE_PRODUCT_REQUESTING = 'UPDATE_PRODUCT_REQUESTING'
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS'
export const UPDATE_PRODUCT_ERROR = 'UPDATE_PRODUCT_ERROR'
export const GET_PRODUCT_INFO_REQUESTING = 'GET_PRODUCT_INFO_REQUESTING'
export const GET_PRODUCT_INFO_SUCCESS = 'GET_PRODUCT_INFO_SUCCESS'
export const GET_PRODUCT_INFO_ERROR = 'GET_PRODUCT_INFO_ERROR'
export const TOGGLE_PRODUCT_STATUS_REQUESTING = 'TOGGLE_PRODUCT_STATUS_REQUESTING'
export const TOGGLE_PRODUCT_STATUS_SUCCESS = 'TOGGLE_PRODUCT_STATUS_SUCCESS'
export const TOGGLE_PRODUCT_STATUS_ERROR = 'TOGGLE_PRODUCT_STATUS_ERROR'

// Foodmaker
export const GET_FOODMAKER_INFO_REQUESTING = 'GET_FOODMAKER_INFO_REQUESTING'
export const GET_FOODMAKER_INFO_SUCCESS = 'GET_FOODMAKER_INFO_SUCCESS'
export const GET_FOODMAKER_INFO_ERROR = 'GET_FOODMAKER_INFO_ERROR'
export const GET_FOODMAKER_INFO_BY_NAME_REQUESTING = 'GET_FOODMAKER_INFO_BY_NAME_REQUESTING'
export const GET_FOODMAKER_INFO_BY_NAME_SUCCESS = 'GET_FOODMAKER_INFO_BY_NAME_SUCCESS'
export const GET_FOODMAKER_INFO_BY_NAME_ERROR = 'GET_FOODMAKER_INFO_BY_NAME_ERROR'
export const CREATE_WITHDRAW_REQUESTING = 'CREATE_WITHDRAW_REQUESTING'
export const CREATE_WITHDRAW_SUCCESS = 'CREATE_WITHDRAW_SUCCESS'
export const CREATE_WITHDRAW_ERROR = 'CREATE_WITHDRAW_ERROR'

// Shop
export const UPDATE_SHOP_REQUESTING = 'UPDATE_SHOP_REQUESTING'
export const UPDATE_SHOP_SUCCESS = 'UPDATE_SHOP_SUCCESS'
export const UPDATE_SHOP_ERROR = 'UPDATE_SHOP_ERROR'
export const CREATE_SHOP_REQUESTING = 'CREATE_SHOP_REQUESTING'
export const CREATE_SHOP_SUCCESS = 'CREATE_SHOP_SUCCESS'
export const CREATE_SHOP_ERROR = 'CREATE_SHOP_ERROR'
export const GET_SHOP_BY_FM_ID_REQUESTING = 'GET_SHOP_BY_FM_ID_REQUESTING'
export const GET_SHOP_BY_FM_ID_SUCCESS = 'GET_SHOP_BY_FM_ID_SUCCESS'
export const GET_SHOP_BY_FM_ID_ERROR = 'GET_SHOP_BY_FM_ID_ERROR'
export const GET_SHOP_BY_URL_REQUESTING = 'GET_SHOP_BY_URL_REQUESTING'
export const GET_SHOP_BY_URL_SUCCESS = 'GET_SHOP_BY_URL_SUCCESS'
export const GET_SHOP_BY_URL_ERROR = 'GET_SHOP_BY_URL_ERROR'

// System
export const GET_PRODUCT_TYPES_REQUESTING = 'GET_PRODUCT_TYPES_REQUESTING'
export const GET_PRODUCT_TYPES_SUCCESS = 'GET_PRODUCT_TYPES_SUCCESS'
export const GET_PRODUCT_TYPES_ERROR = 'GET_PRODUCT_TYPES_ERROR'
export const GET_SERVICE_TAGS_REQUESTING = 'GET_SERVICE_TAGS_REQUESTING'
export const GET_SERVICE_TAGS_SUCCESS = 'GET_SERVICE_TAGS_SUCCESS'
export const GET_SERVICE_TAGS_ERROR = 'GET_SERVICE_TAGS_ERROR'
export const GET_SPECIALITY_TAGS_REQUESTING = 'GET_SPECIALITY_TAGS_REQUESTING'
export const GET_SPECIALITY_TAGS_SUCCESS = 'GET_SPECIALITY_TAGS_SUCCESS'
export const GET_SPECIALITY_TAGS_ERROR = 'GET_SPECIALITY_TAGS_ERROR'
export const GET_PRODUCT_TAGS_REQUESTING = 'GET_PRODUCT_TAGS_REQUESTING'
export const GET_PRODUCT_TAGS_SUCCESS = 'GET_PRODUCT_TAGS_SUCCESS'
export const GET_PRODUCT_TAGS_ERROR = 'GET_PRODUCT_TAGS_ERROR'
export const GET_CITIES_REQUESTING = 'GET_CITIES_REQUESTING'
export const GET_CITIES_SUCCESS = 'GET_CITIES_SUCCESS'
export const GET_CITIES_ERROR = 'GET_CITIES_ERROR'
export const GET_COUNTRIES_REQUESTING = 'GET_COUNTRIES_REQUESTING'
export const GET_COUNTRIES_SUCCESS = 'GET_COUNTRIES_SUCCESS'
export const GET_COUNTRIES_ERROR = 'GET_COUNTRIES_ERROR'

// Pages
export const GET_PUBLIC_PRODUCTS = 'GET_PUBLIC_PRODUCTS'
export const GET_PUBLIC_PRODUCTS_SUCCESS = 'GET_PUBLIC_PRODUCTS_SUCCESS'
export const GET_PUBLIC_PRODUCTS_ERROR = 'GET_PUBLIC_PRODUCTS_ERROR'
export const GET_PUBLIC_FOODMAKERS = 'GET_PUBLIC_FOODMAKERS'
export const GET_PUBLIC_FOODMAKERS_SUCCESS = 'GET_PUBLIC_FOODMAKERS_SUCCESS'
export const GET_PUBLIC_FOODMAKERS_ERROR = 'GET_PUBLIC_FOODMAKERS_ERROR'
export const RESOLVE_FOODMAKER_DATA = 'RESOLVE_FOODMAKER_DATA'

// Stripe
export const GET_STRIPE_TOKEN_REQUESTING = 'GET_STRIPE_TOKEN_REQUESTING'
export const GET_STRIPE_TOKEN_SUCCESS = 'GET_STRIPE_TOKEN_SUCCESS'
export const GET_STRIPE_TOKEN_ERROR = 'GET_STRIPE_TOKEN_ERROR'

// test
export const ACTION_TEST = 'ACTION_TEST'
export const SET_TEST_DATA = 'SET_TEST_DATA'
export const SET_CONNECTION_STATE = 'SET_CONNECTION_STATE'

// SIGN IN
export const NEW_LOGIN_REQUESTING = 'NEW_LOGIN_REQUESTING'
export const NEW_LOGIN_SUCCESS = 'NEW_LOGIN_SUCCESS'
export const NEW_LOGIN_ERROR = 'NEW_LOGIN_ERROR'
export const NEW_LOGOUT = 'NEW_LOGOUT'

// export const LOGIN_EXISTING = 'LOGIN_EXISTING';
export const LOGOUT = 'LOGOUT'

// TOKEN
export const REFRESH_TOKEN_REQUESTING = 'REFRESH_TOKEN_REQUESTING'
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS'
export const REFRESH_TOKEN_ERROR = 'REFRESH_TOKEN_ERROR'

// CHECK NAME
export const CHECK_NAME_REQUESTING = 'CHECK_NAME_REQUESTING'
export const NAME_ALREADY_EXISTS = 'NAME_ALREADY_EXISTS'
export const CHECK_NAME_SUCCESS = 'CHECK_NAME_SUCCESS'
export const CHECK_NAME_ERROR = 'ERROR'
export const NEW_INPUT = 'NEW_INPUT'

// CART
export const ADD_PRODUCT_TO_BASKET = 'ADD_PRODUCT_TO_BASKET'
export const SET_ITEM_TO_PRODUCTS = 'SET_ITEM_TO_PRODUCTS'
export const DELETE_ITEM_FROM_PRODUCTS = 'DELETE_ITEM_FROM_PRODUCTS'
export const SET_ITEM_IN_ORDERS = 'SET_ITEM_IN_ORDERS'
export const SET_SHOP_DATA = 'SET_SHOP_DATA'
export const INC_PRODUCT_AMOUNT = 'INC_PRODUCT_AMOUNT'
export const DEC_PRODUCT_AMOUNT = 'DEC_PRODUCT_AMOUNT'
export const CHANGE_DELIVERY_TYPE = 'CHANGE_DELIVERY_TYPE'
export const ADD_ITEM_TO_ORDER = 'ADD_ITEM_TO_ORDER'
export const DELETE_PRODUCT_FROM_LIST = 'DELETE_PRODUCT_FROM_LIST'
export const DELETE_PRODUCT_AND_SHOP_FROM_LIST = 'DELETE_PRODUCT_AND_SHOP_FROM_LIST'

// FOODMAKER_ORDERS
export const GET_FOODMAKER_ORDERS_REQUESTING = 'GET_FOODMAKER_ORDERS_REQUESTING'
export const GET_FOODMAKER_ORDERS_SUCCESS = 'GET_FOODMAKER_ORDERS_SUCCESS'
export const GET_FOODMAKER_ORDERS_ERROR = 'GET_FOODMAKER_ORDERS_ERROR'
export const GET_FM_ORDER_REQUESTING = 'GET_FM_ORDER_REQUESTING'
export const GET_FM_ORDER_SUCCESS = 'GET_FM_ORDER_SUCCESS'
export const GET_FM_ORDER_ERROR = 'GET_FM_ORDER_ERROR'
export const REMOVE_FM_ORDER = 'REMOVE_FM_ORDER'
export const CHANGE_DELIVERY_STATUS = 'CHANGE_DELIVERY_STATUS'

// FOODLOVER_ORDERS
export const GET_FOODLOVER_ORDERS_REQUESTING = 'GET_FOODLOVER_ORDERS_REQUESTING'
export const GET_FOODLOVER_ORDERS_SUCCESS = 'GET_FOODLOVER_ORDERS_SUCCESS'
export const GET_FOODLOVER_ORDERS_ERROR = 'GET_FOOdLOVER_ORDERS_ERROR'
export const GET_FL_ORDER_REQUESTING = 'GET_FL_ORDER_REQUESTING'
export const GET_FL_ORDER_SUCCESS = 'GET_FL_ORDER_SUCCESS'
export const GET_FL_ORDER_ERROR = 'GET_FL_ORDER_ERROR'
export const REMOVE_FL_ORDER = 'REMOVE_FL_ORDER'

// BILLING_HISTORY
export const GET_BILLING_HISTORY_REQUESTING = 'GET_BILLING_HISTORY_REQUESTING'
export const GET_BILLING_HISTORY_SUCCESS = 'GET_BILLING_HISTORY_SUCCESS'
export const GET_BILLING_HISTORY_ERROR = 'GET_BILLING_HISTORY_ERROR'

// STRIPE
export const CREATE_ORDER_REQUESTING = 'CREATE_ORDER_REQUESTING'
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'
export const CREATE_ORDER_ERROR = 'CREATE_ORDER_ERROR'

// ADMIN
export const GET_USERS_LIST_REQUESTING = 'GET_USERS_LIST_REQUESTING'
export const GET_USERS_LIST_SUCCESS = 'GET_USERS_LIST_SUCCESS'
export const GET_USERS_LIST_ERROR = 'GET_USERS_LIST_ERROR'
export const GET_SHOPS_LIST_REQUESTING = 'GET_SHOPS_LIST_REQUESTING'
export const GET_SHOPS_LIST_SUCCESS = 'GET_SHOPS_LIST_SUCCESS'
export const GET_SHOPS_LIST_ERROR = 'GET_SHOPS_LIST_ERROR'
export const GET_WITHDRAW_LIST_REQUESTING = 'GET_WITHDRAW_LIST_REQUESTING'
export const GET_WITHDRAW_LIST_SUCCESS = 'GET_WITHDRAW_LIST_SUCCESS'
export const GET_WITHDRAW_LIST_ERROR = 'GET_WITHDRAW_LIST_ERROR'
export const APPROVE_WITHDRAW_REQUESTING = 'APPROVE_WITHDRAW_REQUESTING'
export const APPROVE_WITHDRAW_SUCCESS = 'APPROVE_WITHDRAW_SUCCESS'
export const APPROVE_WITHDRAW_ERROR = 'APPROVE_WITHDRAW_ERROR'

// FAVOURITES
export const TOGGLE_FAVOURITE = 'TOGGLE_FAVOURITE'

// SEARCH
export const SEARCH_REQUESTING = 'SEARCH_REQUESTING'
export const SEARCH_ERROR = 'SEARCH_ERROR'
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS'
export const CLEAR_SEARCH_DATA = 'CLEAR_SEARCH_DATA'

// CHAT
export const DISPATCH_MSG = 'DISPATCH_MSG'
export const SET_DIALOG = 'SET_DIALOG'
export const SET_DIALOGS = 'SET_DIALOGS'
export const NEW_DIALOG = 'NEW_DIALOG'
export const ADD_NEW_DIALOG = 'ADD_NEW_DIALOG'
export const SET_ACTIVE_CHAT = 'SET_ACTIVE_CHAT'
export const SET_SOCKET = 'SET_SOCKET'
export const SET_PAGE = 'SET_PAGE'
export const SET_CHAT_HEIGHT = 'SET_CHAT_HEIGHT'
export const SET_NEW_CONTACT = 'SET_NEW_CONTACT'
