// SIGN UP
export const CREATE_NEW_USER = 'CREATE_NEW_USER'
export const CREATE_NEW_USER_REQUESTING = 'CREATE_NEW_USER_REQUESTING'
export const CREATE_NEW_USER_SUCCESS = 'CREATE_NEW_USER_SUCCESS'
export const CREATE_NEW_USER_ERROR = 'CREATE_NEW_USER_ERROR'
export const CANCEL_SIGN_UP = 'CANCEL_SIGN_UP'

// Sign In
export const SIGNUP_REQUESTING = 'SIGNUP_REQUESTING'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_ERROR = 'SIGNUP_ERROR'
export const SIGNUP_FLAG_RESET = 'SIGNUP_FLAG_RESET'

// Login
export const LOGIN_REQUESTING = 'LOGIN_REQUESTING'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGIN_ERROR_RESET = 'LOGIN_ERROR_RESET'

// Forgot STEP 1
export const PASSWORD_REQUESTING = 'PASSWORD_REQUESTING'
export const PASSWORD_REQUESTING_SUCCESS = 'PASSWORD_REQUESTING_SUCCESS'
export const PASSWORD_REQUESTING_ERROR = 'PASSWORD_REQUESTING_ERROR'

// Forgot STEP 1
export const PASSWORD_CREATING = 'PASSWORD_CREATING'
export const PASSWORD_CREATING_SUCCESS = 'PASSWORD_CREATING_SUCCESS'
export const PASSWORD_CREATING_ERROR = 'PASSWORD_CREATING_ERROR'

//
//
//
// ======================================================

// test
export const ACTION_TEST = 'ACTION_TEST'
export const SET_TEST_DATA = 'SET_TEST_DATA'
export const SET_CONNECTION_STATE = 'SET_CONNECTION_STATE'

// SIGN IN
export const NEW_LOGIN_REQUESTING = 'NEW_LOGIN_REQUESTING'
export const NEW_LOGIN_SUCCESS = 'NEW_LOGIN_SUCCESS'
export const NEW_LOGIN_ERROR = 'NEW_LOGIN_ERROR'
export const NEW_LOGOUT = 'NEW_LOGOUT'

// export const LOGIN_EXISTING = 'LOGIN_EXISTING';
export const LOGOUT = 'LOGOUT'

// TOKEN
export const REFRESH_TOKEN_REQUESTING = 'REFRESH_TOKEN_REQUESTING'
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS'
export const REFRESH_TOKEN_ERROR = 'REFRESH_TOKEN_ERROR'

// CHECK NAME
export const CHECK_NAME_REQUESTING = 'CHECK_NAME_REQUESTING'
export const NAME_ALREADY_EXISTS = 'NAME_ALREADY_EXISTS'
export const CHECK_NAME_SUCCESS = 'CHECK_NAME_SUCCESS'
export const CHECK_NAME_ERROR = 'ERROR'
export const NEW_INPUT = 'NEW_INPUT'
