import {
  GET_UNREVIEWED_PRODUCT_REQUESTING,
  GET_UNREVIEWED_PRODUCT_SUCCESS,
  GET_UNREVIEWED_PRODUCT_ERROR,
  CREATE_PRODUCT_REVIEW_REQUESTING,
  CREATE_PRODUCT_REVIEW_SUCCESS,
  CREATE_PRODUCT_REVIEW_ERROR,
  GET_FL_REVIEWS_REQUESTING,
  GET_FL_REVIEWS_SUCCESS,
  GET_FL_REVIEWS_ERROR,
} from './constants'

export const getUnreviewedProductAC = () => ({
  type: GET_UNREVIEWED_PRODUCT_REQUESTING,
})

export const getUnreviewedProductSuccess = (data) => ({
  type: GET_UNREVIEWED_PRODUCT_SUCCESS,
  data,
})
